import type { NextPage } from "next";
import Head from "next/head";
import { Center, Heading, VStack, Text } from "@chakra-ui/react";
import React from "react";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Flashcards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center h="100vh">
        <VStack spacing={8}>
          <Text color="white">Choose language...</Text>
          <Link href="/cards/french" passHref>
            <Heading
              backgroundClip="text"
              animation="language 2s infinite alternate"
              sx={{
                "background-clip": "text",
              }}
              backgroundImage="linear-gradient(to right, blue 20%, white 50%, red 80%)"
              _hover={{
                animationPlayState: "paused",
                cursor: "pointer",
              }}
            >
              French
            </Heading>
          </Link>
          <Link href="/cards/japanese" passHref>
            <Heading
              animation="language 2s infinite alternate"
              sx={{
                "background-clip": "text",
              }}
              backgroundClip="text"
              backgroundImage="linear-gradient(to right, white 20%, red 50%, white 80%)"
              _hover={{
                animationPlayState: "paused",
                cursor: "pointer",
              }}
            >
              Japanese
            </Heading>
          </Link>
        </VStack>
      </Center>
    </>
  );
};

export default Home;
