import type { NextPage } from "next";
import Head from "next/head";
import { Center, Heading, VStack, Text } from "@chakra-ui/react";
import React from "react";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Flashcards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center h="100vh">
        <VStack spacing={8}>
          <Text>Choose lang</Text>
          <Link href="/cards/french" passHref>
            <Heading>French</Heading>
          </Link>
          <Link href="/cards/japanese" passHref>
            <Heading>Japanese</Heading>
          </Link>
        </VStack>
      </Center>
    </>
  );
};

export default Home;
